CREATE DATABASE CuaHangMayTinh
GO
USE CuaHangMayTinh
GO


CREATE TABLE BRAND(
	BRD_ID VARCHAR(100) PRIMARY KEY,
	BRD_NAME NVARCHAR(255) NOT NULL,
	BRD_ADDRESS NVARCHAR(100),
	BRD_PHONE VARCHAR(10),
	BRD_EMAIL VARCHAR(100),
	BRD_STATUS NVARCHAR(255) --Trạng thái (Đang hợp tác, dừng hợp tác...)
);
GO

CREATE TABLE POSITION(
	PS_ID VARCHAR(100) PRIMARY KEY,
	PS_NAME NVARCHAR(255) NOT NULL,
	PS_NOTE NVARCHAR(255),
)
GO

CREATE TABLE AUTHORITY(
	AUT_ID VARCHAR(100) PRIMARY KEY,
	AUT_NAME NVARCHAR(255) NOT NULL
)
GO

CREATE TABLE POSITION_AUTHORITY(
	ID VARCHAR(100) PRIMARY KEY,
	PS_ID VARCHAR(100) FOREIGN KEY REFERENCES POSITION(PS_ID),
    AUT_ID VARCHAR(100) FOREIGN KEY REFERENCES AUTHORITY(AUT_ID),
	ROLE_TYPE NVARCHAR(50) --'Đọc và ghi','Chỉ đọc', 'Không có quyền'
)
GO

CREATE TABLE EMPLOYEES(
	EMP_ID VARCHAR(100) PRIMARY KEY,
	EMP_NAME NVARCHAR(255) NOT NULL,
	EMP_PHONE_NUMBER VARCHAR(10) NOT NULL,
	EMP_BIRTHDAY DATE NOT NULL,
	EMP_GENDER NVARCHAR(3),
	EMP_PROVINCE NVARCHAR(255),
	EMP_DISTRICT NVARCHAR(255), 
	EMP_WARD NVARCHAR(255),
	EMP_ADDRESS NVARCHAR(255) NOT NULL,
	EMP_EMAIL VARCHAR(100) NOT NULL,
	EMP_ACCOUNT VARCHAR(20) NOT NULL,
	EMP_PASSWORD VARCHAR(20) NOT NULL,
	HIRE_DATE DATETIME,
	PS_ID VARCHAR(100) FOREIGN KEY REFERENCES POSITION(PS_ID),
	EMP_STATUS NVARCHAR(255),
--	CONSTRAINT FK_EMPLOYEES_PROVINCES FOREIGN KEY (EMP_PROVINCE) REFERENCES provinces(name),
--	CONSTRAINT FK_EMPLOYEES_DISTRICTS FOREIGN KEY (EMP_DISTRICT) REFERENCES districts(name),
--	CONSTRAINT FK_EMPLOYEES_WARD FOREIGN KEY (EMP_WARD) REFERENCES wards(name)
);
GO

CREATE TABLE CUSTOMER (
    CUS_ID VARCHAR(100) PRIMARY KEY,
    CUS_NAME NVARCHAR(255) NOT NULL,
	CUS_BIRTHDAY DATE,
	CUS_GENDER NVARCHAR(3),
	CUS_PHONE_NUMBER VARCHAR(10) NOT NULL,
    CUS_ADDRESS NVARCHAR(255) NOT NULL,
	CUS_TOTAL_SPENDING_MONEY INT,
	CUS_TOTAL_PRODUCTS_PURCHASED INT,
	CUS_TOTAL_QUANTITY_OF_ORDER INT,
	CUS_DATE_OF_LAST_PURCHASE DATE,
);
GO

CREATE TABLE PRODUCTTYPE(
	PRD_TYPE_ID NVARCHAR(50) PRIMARY KEY,
	PRD_TYPE_NAME NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE PRODUCT (
	PRD_IMG VARCHAR(1000), 
    PRD_ID VARCHAR(100) PRIMARY KEY,
    PRD_NAME NVARCHAR(255) NOT NULL,
    PRD_TYPE_ID NVARCHAR(50) NOT NULL,
    BRD_ID NVARCHAR(50) NOT NULL,
    RDY_FOR_SALE INT NOT NULL,
    QUANTITY INT NOT NULL,
	DELIVERY_ALLOWED BIT NOT NULL,
	PRD_WEIGHT FLOAT,
	CONSTRAINT FK_PRODUCT_BRAND FOREIGN KEY (PRD_ID) REFERENCES BRAND(BRD_ID),
	CONSTRAINT FK_PRODUCT_PRODUCTTYPE FOREIGN KEY (PRD_TYPE_ID) REFERENCES PRODUCTTYPE(PRD_TYPE_ID)
);
GO

CREATE TABLE WAREHOUSE(
	PRD_IMG VARCHAR(1000),
	PRD_ID VARCHAR(100) PRIMARY KEY,
	PRD_NAME NVARCHAR(100) NOT NULL,
	PRD_TYPE_ID NVARCHAR(50) NOT NULL,
	BRD_ID VARCHAR(100) NOT NULL,
	RDY_FOR_SALE INT NOT NULL,
	INVENTORY_QUANTITY INT NOT NULL, 
	CREATE_DAY DATE,
	RETAIL_PRICE FLOAT NOT NULL,
	IMPORT_PRICE FLOAT NOT NULL,
	WHOLESALE_PRICE FLOAT NOT NULL
	CONSTRAINT FK_WAREHOUSE_BRAND FOREIGN KEY (BRD_ID) REFERENCES BRAND(BRD_ID),
	CONSTRAINT FK_WAREHOUSE_PRODUCTTYPE FOREIGN KEY (PRD_TYPE_ID) REFERENCES PRODUCTTYPE(PRD_TYPE_ID)
)
GO

CREATE TABLE PAYMENT (
	PMT_NAME NVARCHAR(50) PRIMARY KEY
);
GO

CREATE TABLE DISCOUNT(
	CODE VARCHAR(100) PRIMARY KEY,
	DISCOUNT_PERCENT FLOAT,
	MAXIMUM_USE INT,
	USED_COUNT INT,
	MAXIMUM_DISCOUNT_AMOUNT FLOAT
); 
GO

CREATE TABLE SALEBILL (
    SL_ID VARCHAR(100) PRIMARY KEY,
    SL_DATE DATE NOT NULL,
    CUS_ID VARCHAR(100) NOT NULL,
    EMP_ID VARCHAR(100) NOT NULL, 
	DISCOUNT_CODE VARCHAR(100),
    TOTAL_MONEY FLOAT,
    PAYMENT NVARCHAR(50) NOT NULL,
    NOTE NVARCHAR(255),
	MONEY_CUSTOMER_GIVE FLOAT,
	REFUND FLOAT,
	STATUS NVARCHAR(255),
    CONSTRAINT FK_SALEBILL_CUSTOMER FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID),
    CONSTRAINT FK_SALEBILL_EMPLOYEES FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID),
	CONSTRAINT FK_SALEBILL_DISCOUNT FOREIGN KEY (DISCOUNT_CODE) REFERENCES DISCOUNT(CODE),
	CONSTRAINT FK_SALEBILL_PAYMENT FOREIGN KEY (PAYMENT) REFERENCES PAYMENT(PMT_NAME)
);
GO

CREATE TABLE SALEBILL_DETAIL (
	SL_DETAIL_ID VARCHAR(100) PRIMARY KEY,
    SL_ID VARCHAR(100) NOT NULL,
    PRD_ID VARCHAR(100) NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE FLOAT,
    CONSTRAINT FK_SALEBILL_DETAIL_SALEBILL FOREIGN KEY (SL_ID) REFERENCES SALEBILL(SL_ID),
    CONSTRAINT FK_SALEBILL_DETAIL_PRODUCT FOREIGN KEY (PRD_ID) REFERENCES PRODUCT(PRD_ID)
);
GO

CREATE TABLE IMPORTBILL(
	IB_ID VARCHAR(100) PRIMARY KEY,
	BRD_ID VARCHAR(100) NOT NULL,
	EMP_ID VARCHAR(100) NOT NULL,
	IB_DATE DATETIME NOT NULL,
	TOTAL_MONEY FLOAT,
	NOTE NVARCHAR(255),
	CONSTRAINT FK_IMPORTBILL_BRAND FOREIGN KEY (BRD_ID) REFERENCES BRAND(BRD_ID),
    CONSTRAINT FK_IMPORTBILL_EMPLOYEES FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID) 
);
GO

CREATE TABLE IMPORTBILL_DETAIL(
	IB_DETAIL_ID VARCHAR(100) PRIMARY KEY,
	IB_ID VARCHAR(100) NOT NULL,
	PRD_ID VARCHAR(100) NOT NULL,
	QUANTITY INT,
	IB_PRICE FLOAT,
	CONSTRAINT FK_IMPORTBILL_DETAIL_IMPORTBILL FOREIGN KEY (IB_ID) REFERENCES IMPORTBILL(IB_ID),
    CONSTRAINT FK_IMPORTBILL_DETAIL_PRODUCT FOREIGN KEY (PRD_ID) REFERENCES PRODUCT(PRD_ID) 
);
GO







alter PROC PROC_LOGIN
@username VARCHAR(255),
@password VARCHAR(255)
AS
BEGIN
	SELECT * FROM EMPLOYEES WHERE EMP_ACCOUNT = @username AND EMP_PASSWORD = @password
END

exec PROC_LOGIN 'admin', 'admin'
