//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRAND
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BRAND()
        {
            this.IMPORTBILLs = new HashSet<IMPORTBILL>();
            this.WAREHOUSEs = new HashSet<WAREHOUSE>();
        }
    
        public string BRD_ID { get; set; }
        public string BRD_NAME { get; set; }
        public string BRD_ADDRESS { get; set; }
        public string BRD_PHONE { get; set; }
        public string BRD_EMAIL { get; set; }
        public string BRD_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPORTBILL> IMPORTBILLs { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAREHOUSE> WAREHOUSEs { get; set; }
    }
}
