//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.SALEBILLs = new HashSet<SALEBILL>();
        }
    
        public string CUS_ID { get; set; }
        public string CUS_NAME { get; set; }
        public Nullable<System.DateTime> CUS_BIRTHDAY { get; set; }
        public string CUS_GENDER { get; set; }
        public string CUS_PHONE_NUMBER { get; set; }
        public string CUS_ADDRESS { get; set; }
        public Nullable<int> CUS_TOTAL_SPENDING_MONEY { get; set; }
        public Nullable<int> CUS_TOTAL_PRODUCTS_PURCHASED { get; set; }
        public Nullable<int> CUS_TOTAL_QUANTITY_OF_ORDER { get; set; }
        public Nullable<System.DateTime> CUS_DATE_OF_LAST_PURCHASE { get; set; }
        public string EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALEBILL> SALEBILLs { get; set; }
    }
}
