//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCOUNT
    {
        public string CODE { get; set; }
        public Nullable<decimal> DISCOUNT_PERCENT { get; set; }
        public Nullable<decimal> DISCOUNT_AMOUNT { get; set; }
        public Nullable<decimal> MAXIMUM_DISCOUNT_AMOUNT { get; set; }
        public string CODE_DESCRIPTION { get; set; }
        public Nullable<decimal> MIN_PURCHASE_VALUE { get; set; }
        public Nullable<int> MIN_QUANTITY_OF_PRODUCT { get; set; }
        public Nullable<int> MAXIMUM_USE { get; set; }
        public Nullable<int> USED_COUNT { get; set; }
        public Nullable<System.DateTime> DISCOUNT_START_DATE { get; set; }
        public Nullable<System.DateTime> DISCOUNT_END_DATE { get; set; }
        public string DISCOUNT_STATUS { get; set; }
    }
}
