//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public string EMP_ID { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_PHONE_NUMBER { get; set; }
        public System.DateTime EMP_BIRTHDAY { get; set; }
        public string EMP_GENDER { get; set; }
        public string EMP_ADDRESS { get; set; }
        public string EMP_EMAIL { get; set; }
        public string EMP_ACCOUNT { get; set; }
        public string EMP_PASSWORD { get; set; }
        public Nullable<System.DateTime> HIRE_DATE { get; set; }
        public string PS_ID { get; set; }
        public string EMP_STATUS { get; set; }
    
        public virtual POSITION POSITION { get; set; }
    }
}
