//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.IMPORTBILLs = new HashSet<IMPORTBILL>();
            this.SALEBILLs = new HashSet<SALEBILL>();
        }
    
        public string EMP_ID { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_PHONE_NUMBER { get; set; }
        public System.DateTime EMP_BIRTHDAY { get; set; }
        public string EMP_GENDER { get; set; }
        public string EMP_PROVINCE { get; set; }
        public string EMP_DISTRICT { get; set; }
        public string EMP_WARD { get; set; }
        public string EMP_ADDRESS { get; set; }
        public string EMP_EMAIL { get; set; }
        public string EMP_ACCOUNT { get; set; }
        public string EMP_PASSWORD { get; set; }
        public Nullable<System.DateTime> HIRE_DATE { get; set; }
        public string PS_ID { get; set; }
        public string EMP_STATUS { get; set; }
    
        public virtual POSITION POSITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPORTBILL> IMPORTBILLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALEBILL> SALEBILLs { get; set; }
    }
}
