//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORTBILL_DETAIL
    {
        public string IB_DETAIL_ID { get; set; }
        public string IB_ID { get; set; }
        public string PRD_ID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<double> IB_PRICE { get; set; }
    
        public virtual IMPORTBILL IMPORTBILL { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
