//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORTBILL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMPORTBILL()
        {
            this.IMPORTBILL_DETAIL = new HashSet<IMPORTBILL_DETAIL>();
        }
    
        public string IB_ID { get; set; }
        public string BRD_ID { get; set; }
        public string EMP_ID { get; set; }
        public System.DateTime IB_DATE { get; set; }
        public Nullable<double> TOTAL_MONEY { get; set; }
        public string NOTE { get; set; }
    
        public virtual BRAND BRAND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPORTBILL_DETAIL> IMPORTBILL_DETAIL { get; set; }
    }
}
