//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSITION_AUTHORITY
    {
        public string ID { get; set; }
        public string PS_ID { get; set; }
        public string AUT_ID { get; set; }
    
        public virtual AUTHORITY AUTHORITY { get; set; }
        public virtual POSITION POSITION { get; set; }
    }
}
