//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public string PRD_IMG { get; set; }
        public string PRD_ID { get; set; }
        public string PRD_NAME { get; set; }
        public string PRD_TYPE_ID { get; set; }
        public string BRD_ID { get; set; }
        public int RDY_FOR_SALE { get; set; }
        public int QUANTITY { get; set; }
        public bool DELIVERY_ALLOWED { get; set; }
        public Nullable<double> PRD_WEIGHT { get; set; }
        public Nullable<System.DateTime> CREATE_DAY { get; set; }
    
        public virtual PRODUCTTYPE PRODUCTTYPE { get; set; }
    }
}
