//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMOTION
    {
        public string PROMOTION_ID { get; set; }
        public string PROMOTION_NAME { get; set; }
        public string PROMOTION_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> PROMOTION_START_DATE { get; set; }
        public Nullable<System.DateTime> PROMOTION_END_DATE { get; set; }
        public Nullable<decimal> DISCOUNT_PERCENT { get; set; }
        public Nullable<decimal> DISCOUNT_AMOUNT { get; set; }
        public string PRD_TYPE_NAME { get; set; }
        public string PRD_NAME { get; set; }
        public Nullable<decimal> MIN_PURCHASE_VALUE { get; set; }
        public Nullable<int> MIN_QUANTITY_OF_PRODUCT { get; set; }
        public Nullable<int> MAXIMUM_USE { get; set; }
        public Nullable<int> USED_COUNT { get; set; }
        public string PROMOTION_STATUS { get; set; }
    }
}
