//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALEBILL_DETAIL
    {
        public string SL_DETAIL_ID { get; set; }
        public string SL_ID { get; set; }
        public string PRD_ID { get; set; }
        public int QUANTITY { get; set; }
        public Nullable<double> PRICE { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual SALEBILL SALEBILL { get; set; }
    }
}
