//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAREHOUSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WAREHOUSE()
        {
            this.IMPORTBILL_DETAIL = new HashSet<IMPORTBILL_DETAIL>();
        }
    
        public string PRD_IMG { get; set; }
        public string PRD_ID { get; set; }
        public string PRD_NAME { get; set; }
        public string PRD_TYPE_ID { get; set; }
        public string BRD_ID { get; set; }
        public int RDY_FOR_SALE { get; set; }
        public int INVENTORY_QUANTITY { get; set; }
        public Nullable<System.DateTime> CREATE_DAY { get; set; }
        public double RETAIL_PRICE { get; set; }
        public double IMPORT_PRICE { get; set; }
        public double WHOLESALE_PRICE { get; set; }
    
        public virtual BRAND BRAND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPORTBILL_DETAIL> IMPORTBILL_DETAIL { get; set; }
        public virtual PRODUCTTYPE PRODUCTTYPE { get; set; }
    }
}
